apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite
spec:
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mywebsite
        image: archsarangx/mywebsite
        resources:
          limits:
            memory: '128Mi'
            cpu: '500m'
        ports:
          - containerPort: 80

